module.exports.registeredOrigins = {
  "https://backtrackhq.web.app": new Set([
    "youtube.com",
    "ytimg.com",
    "duckduckgo.com",
    "googlevideo.com",
  ]),
  "https://r34.app": new Set([
    "rule34.xxx",
    "gelbooru.com",
    "rule34.paheal.net",
    "danbooru.donmai.us",
    "e621.net",
    "e926.net",
    "safebooru.org",
    "realbooru.com",
    "tbib.org",
    "xbooru.com",
    "yande.re",
    "konachan.com",
    "hypnohub.net",
    "aibooru.online",
    "e6ai.net",
    "booru.allthefallen.moe",
    "sakugabooru.com",
  ]),
};
